### ISSUE TITLE
[Main] 새로운 메인구성 어때요??

### ISSUE THREAD

**Issue by kkkimjiyong** [kkkimjiyong/BoardWith_FE#34]
# 이슈템플릿

## [페이지]기능

- 메인페이지에 아래 사진과 같이, 구성을 살짝 바꾸어보아도 괜찮을까요?
![뽀득뽀득 새로운 메인구성](https://user-images.githubusercontent.com/113953473/201541865-0fe007b0-a978-4677-9da7-18b37f0ebf94.jpg)

## 변경될 로직

- 거리순으로 나열하는 기능은 이미 구현되어있고, 슬라이드도 구현되어있으니 구성만 바꾸면 될 듯 합니다.

**Comment by kkkimjiyong** [comment]
필터가 적용되었을 때에도 페이지구성이 달라져야겠네요. 지금과 같이 일열로 나열되는 식으로?

**Comment by kasucco** [comment]
메인에  해시태그 추천이 뜨는건가요? 필터했을 때 페이지 구성이 달라진다는건 어떤걸 말하시는 거죠??
